version: 2
jobs:
    build:
        working_directory: /go/src/
        docker:
            - image: golang:latest
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.05.0-ce
            - run:
                name: install Docker clinet
                command: |
                    set -x
                    VER="17.05.0-ce"
                    curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                    tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                    mv /tmp/docker/* /usr/bin

                    docker version
            - run:
                name: build docker image
                command: |
                    docker build -t goapp .
            - run:
                name: running test
                command: |
                  docker run -d --net=host -p 8080:8080 goapp
                  docker run --rm --net=host container:api appropriate/curl \
                    --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/

            - deploy:
                name: Deploy Release Branch
                command: |
                    if [ "${CIRCLE_BRANCH}" == "release" ]; then
                      echo "deploy"
                    fi